"""empty message

Revision ID: 4eab0cd9edc0
Revises: 22c47b6fdab9
Create Date: 2015-05-27 11:45:31.267134

"""

# revision identifiers, used by Alembic.
revision = '4eab0cd9edc0'
down_revision = '22c47b6fdab9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('players', postgresql.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('current_player', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'users', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column(u'users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column(u'users', sa.Column('current_score', sa.Integer(), nullable=True))
    op.add_column(u'users', sa.Column('last_game', sa.Integer(), nullable=True))
    op.drop_constraint(u'users_email_key', 'users', type_='unique')
    op.drop_column(u'users', 'email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'users', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_unique_constraint(u'users_email_key', 'users', ['email'])
    op.drop_column(u'users', 'last_game')
    op.drop_column(u'users', 'current_score')
    op.drop_column(u'users', 'created_at')
    op.drop_column(u'users', 'avatar')
    op.drop_table('games')
    ### end Alembic commands ###
